name: Banana art
favicon: null
layout_spectrum: 0.22377184149809182
typography_spectrum: 0.05822084844112396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7753909728489816
  lightness: 0.72911202092655
  saturation: 0.25633686408400536
  rhythmicContrast: 0.16520361718721688
purpose: []
